apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
        name: site
        namespace: argocd
spec:
        project: default

        source:
                repoURL: https://github.com/mpgrail13/chart.git
                targetRevision: HEAD
                path: charts/helmchart
        destination:
                server: https://kubernetes.default.svc
                namespace: default

        syncPolicy:
                automated:
                        selfHeal: true
                        prune: true
