---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
spec:
  selector:
    app: {{ .Values.deployment.labels }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.deployment.nginx_port }}
      nodePort: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.nginx_port }}
